# Generated by Django 4.2.5 on 2023-11-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(upload_to='page')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayinlandi'), ('delted', 'Silindi')], default='draft', max_length=10)),
                ('created_att', models.DateTimeField(auto_now_add=True)),
                ('uploated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
