# Generated by Django 4.2.5 on 2023-11-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
