# Generated by Django 4.2.5 on 2023-12-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayinlandi'), ('delted', 'Silindi')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Carousel'),
        ),
    ]
