# Generated by Django 4.2.5 on 2023-12-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_carousel_status_alter_carousel_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
