# Generated by Django 4.2.5 on 2023-12-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcart',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shopingcartitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
