# Generated by Django 4.2.5 on 2023-12-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_shopingcart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopingcartitem',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
