# Generated by Django 4.2.5 on 2023-12-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_shopingcartitem_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopingcartitem',
            name='is_hidden',
        ),
    ]
